//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDAL
{
    using System;
    
    public partial class SpGetTransactionPayments_Result
    {
        public int TransactionMasterID { get; set; }
        public int PaymentId { get; set; }
        public decimal PaymentAmount { get; set; }
        public string PaymentType { get; set; }
        public bool IsActive { get; set; }
        public string CreatedByName { get; set; }
        public string UpdateByName { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentDateNepali { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
