//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigChoice
    {
        public int ChoiceId { get; set; }
        public int CategoryId { get; set; }
        public string Choice { get; set; }
        public string ChoiceDescription { get; set; }
        public string ChoiceNepali { get; set; }
        public string Val { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ConfigChoiceCategory ConfigChoiceCategory { get; set; }
    }
}
