//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceCopy
    {
        public ResourceCopy()
        {
            this.ResourceIssues = new HashSet<ResourceIssue>();
        }
    
        public int ResourceCopyId { get; set; }
        public int GenerationId { get; set; }
        public int ResourceId { get; set; }
        public int ResourceCopyCount { get; set; }
        public string ResourceCopyNumber { get; set; }
        public string Remarks { get; set; }
        public bool IsAvailable { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public string Edition { get; set; }
    
        public virtual ResourceGeneration ResourceGeneration { get; set; }
        public virtual ResourceSetup ResourceSetup { get; set; }
        public virtual ICollection<ResourceIssue> ResourceIssues { get; set; }
    }
}
