//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceSetup
    {
        public ResourceSetup()
        {
            this.ResourceCopies = new HashSet<ResourceCopy>();
            this.ResourceGenerations = new HashSet<ResourceGeneration>();
        }
    
        public int ResourceId { get; set; }
        public int ResourceTypeId { get; set; }
        public Nullable<int> PublicationId { get; set; }
        public string PublicationName { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string AuthorName { get; set; }
        public string ResourceName { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual ResourceAuthor ResourceAuthor { get; set; }
        public virtual ICollection<ResourceCopy> ResourceCopies { get; set; }
        public virtual ICollection<ResourceGeneration> ResourceGenerations { get; set; }
        public virtual ResourcePublication ResourcePublication { get; set; }
        public virtual ResourceType ResourceType { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
