//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceIssue
    {
        public int IssueId { get; set; }
        public int ResourceCopyId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ReturnBackDate { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public string Remarks { get; set; }
        public int subscriber { get; set; }
        public bool IsActive { get; set; }
        public bool IsAvailable { get; set; }
    
        public virtual ResourceCopy ResourceCopy { get; set; }
        public virtual ResourceSubscriber ResourceSubscriber { get; set; }
    }
}
